channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - imagemagick=7.1.0_19
  - snakemake-minimal >=5.24.1
  - r-base=4.0.5
  - r-r.utils=2.10.1
  - r-dplyr=1.0.7
  - r-ggplot2=3.3.5
  - r-gridExtra=2.3
  - r-tidyr=1.1.3
  - r-openxlsx=4.2.4
